### ISSUE TITLE
No map loader shown

### ISSUE THREAD

**Issue by hahayespog** [RedBrumbler/MonkeMapLoader#6]
I've got the mod installed 
![image](https://user-images.githubusercontent.com/81516826/129858937-794794c2-a7de-45b5-b35a-4b956407b0d3.png)
And the map
![image](https://user-images.githubusercontent.com/81516826/129858990-1fc99989-535a-415b-9f87-873a3e02cd9d.png)
But in-game there isn't a Map Loader option on the computer nor a teleporter, but other mods work perfectly

1.0.11 Gorilla Tag, Quest 2, Monke Map Loader v1.0.2, QuestPatcher 2

**Comment by Tabletteaccount** [comment]
I have exactly the same problem.

**Comment by hahayespog** [comment]
Turns out it isn't compatible to 1.0.11, the creator is working on it though (I believe)
